name: "Lamb Review Action"
description: "A GitHub Action to streamline your code review process"
author: "Chaejung Kim (blcklamb)"
branding:
  icon: "thumbs-up"
  color: "gray-dark"

inputs:
  GITHUB_TOKEN:
    description: "GitHub Token to authenticate"
    required: true

  OPENAI_API_KEY:
    description: "OpenAI API Key to use GPT"
    required: true

  openai_api_model:
    description: "OpenAI API Model to use GPT"
    required: false
    default: "gpt-4"

  review_rules:
    description: "JSON string of custom review rules"
    required: false
    default: "{}"

  exclude:
    description: "Comma-separated list of file paths to exclude from review"
    required: false
    default: ""

outputs:
  review_success:
    description: "Indicates whether the code review passed or failed"

runs:
  using: "node18"
  main: "dist/index.js"

# Example usage of the action
example:
  - uses: blcklamb/LambReviewAction@v1
    with:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      openai_api_model: "gpt-4"
      review_rules: '{"max_line_length":80,"no_console_log":true}'
      exclude_files: "docs/**,tests/**"
